/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SendUsAMessageRouteImport } from './routes/send-us-a-message'
import { Route as ResourceHubRouteImport } from './routes/resource-hub'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedResultsIdRouteImport } from './routes/_authenticated/results.$id'
import { Route as AuthenticatedQuestionnaireAreaRouteImport } from './routes/_authenticated/questionnaire.$area'
import { Route as AuthenticatedAdminResourcesNewRouteImport } from './routes/_authenticated/admin/resources.new'
import { Route as AuthenticatedAdminResourcesIdEditRouteImport } from './routes/_authenticated/admin/resources.$id.edit'

const SendUsAMessageRoute = SendUsAMessageRouteImport.update({
  id: '/send-us-a-message',
  path: '/send-us-a-message',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourceHubRoute = ResourceHubRouteImport.update({
  id: '/resource-hub',
  path: '/resource-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedResultsIdRoute = AuthenticatedResultsIdRouteImport.update({
  id: '/results/$id',
  path: '/results/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuestionnaireAreaRoute =
  AuthenticatedQuestionnaireAreaRouteImport.update({
    id: '/questionnaire/$area',
    path: '/questionnaire/$area',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminResourcesNewRoute =
  AuthenticatedAdminResourcesNewRouteImport.update({
    id: '/resources/new',
    path: '/resources/new',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminResourcesIdEditRoute =
  AuthenticatedAdminResourcesIdEditRouteImport.update({
    id: '/resources/$id/edit',
    path: '/resources/$id/edit',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/resource-hub': typeof ResourceHubRoute
  '/send-us-a-message': typeof SendUsAMessageRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/questionnaire/$area': typeof AuthenticatedQuestionnaireAreaRoute
  '/results/$id': typeof AuthenticatedResultsIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/resources/new': typeof AuthenticatedAdminResourcesNewRoute
  '/admin/resources/$id/edit': typeof AuthenticatedAdminResourcesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/resource-hub': typeof ResourceHubRoute
  '/send-us-a-message': typeof SendUsAMessageRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/questionnaire/$area': typeof AuthenticatedQuestionnaireAreaRoute
  '/results/$id': typeof AuthenticatedResultsIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/resources/new': typeof AuthenticatedAdminResourcesNewRoute
  '/admin/resources/$id/edit': typeof AuthenticatedAdminResourcesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/resource-hub': typeof ResourceHubRoute
  '/send-us-a-message': typeof SendUsAMessageRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/questionnaire/$area': typeof AuthenticatedQuestionnaireAreaRoute
  '/_authenticated/results/$id': typeof AuthenticatedResultsIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/resources/new': typeof AuthenticatedAdminResourcesNewRoute
  '/_authenticated/admin/resources/$id/edit': typeof AuthenticatedAdminResourcesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/resource-hub'
    | '/send-us-a-message'
    | '/admin'
    | '/dashboard'
    | '/profile'
    | '/questionnaire/$area'
    | '/results/$id'
    | '/admin/'
    | '/admin/resources/new'
    | '/admin/resources/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/resource-hub'
    | '/send-us-a-message'
    | '/dashboard'
    | '/profile'
    | '/questionnaire/$area'
    | '/results/$id'
    | '/admin'
    | '/admin/resources/new'
    | '/admin/resources/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/resource-hub'
    | '/send-us-a-message'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/_authenticated/questionnaire/$area'
    | '/_authenticated/results/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/resources/new'
    | '/_authenticated/admin/resources/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResourceHubRoute: typeof ResourceHubRoute
  SendUsAMessageRoute: typeof SendUsAMessageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/send-us-a-message': {
      id: '/send-us-a-message'
      path: '/send-us-a-message'
      fullPath: '/send-us-a-message'
      preLoaderRoute: typeof SendUsAMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resource-hub': {
      id: '/resource-hub'
      path: '/resource-hub'
      fullPath: '/resource-hub'
      preLoaderRoute: typeof ResourceHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/results/$id': {
      id: '/_authenticated/results/$id'
      path: '/results/$id'
      fullPath: '/results/$id'
      preLoaderRoute: typeof AuthenticatedResultsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/questionnaire/$area': {
      id: '/_authenticated/questionnaire/$area'
      path: '/questionnaire/$area'
      fullPath: '/questionnaire/$area'
      preLoaderRoute: typeof AuthenticatedQuestionnaireAreaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/resources/new': {
      id: '/_authenticated/admin/resources/new'
      path: '/resources/new'
      fullPath: '/admin/resources/new'
      preLoaderRoute: typeof AuthenticatedAdminResourcesNewRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/resources/$id/edit': {
      id: '/_authenticated/admin/resources/$id/edit'
      path: '/resources/$id/edit'
      fullPath: '/admin/resources/$id/edit'
      preLoaderRoute: typeof AuthenticatedAdminResourcesIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminResourcesNewRoute: typeof AuthenticatedAdminResourcesNewRoute
  AuthenticatedAdminResourcesIdEditRoute: typeof AuthenticatedAdminResourcesIdEditRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminResourcesNewRoute: AuthenticatedAdminResourcesNewRoute,
    AuthenticatedAdminResourcesIdEditRoute:
      AuthenticatedAdminResourcesIdEditRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedQuestionnaireAreaRoute: typeof AuthenticatedQuestionnaireAreaRoute
  AuthenticatedResultsIdRoute: typeof AuthenticatedResultsIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedQuestionnaireAreaRoute: AuthenticatedQuestionnaireAreaRoute,
  AuthenticatedResultsIdRoute: AuthenticatedResultsIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResourceHubRoute: ResourceHubRoute,
  SendUsAMessageRoute: SendUsAMessageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
